# Generated by Django 3.2 on 2021-05-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='organizacion',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='terminos_condiciones',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
