# Generated by Django 3.2 on 2021-05-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='organizacion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
