# Generated by Django 3.2 on 2021-06-06 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionModel',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=3, max_digits=10)),
                ('retroalim', models.CharField(default='Sin descripción', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenConfiguracionModel',
            fields=[
                ('id_configuracion_examen', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title_exam', models.CharField(default='Sin título', max_length=200)),
                ('contrasena_exam', models.CharField(max_length=200)),
                ('n_intentos', models.SmallIntegerField(default=1)),
                ('fecha_hora_ini', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('duracion', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneracionModel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('n_examenes', models.SmallIntegerField()),
                ('longit_texto', models.IntegerField(default=200)),
                ('n_preguntas', models.SmallIntegerField()),
                ('inicio_oracion', models.CharField(choices=[('Aleatorio', 'Aleatorio'), ('Personalizado', 'Personalizado'), ('Completo', 'Completo')], max_length=30)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneracionPreguntaModel',
            fields=[
                ('id_pregunta', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pregunta_cuerpo', models.CharField(max_length=1000)),
                ('respuesta_correcta', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaCuerpoModel',
            fields=[
                ('generacion_pregunta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='respuestas_cuerpo', serialize=False, to='gquestions_api.generacionpreguntamodel')),
                ('resp_unica', models.CharField(max_length=1000)),
                ('opcion_multiple', models.CharField(max_length=100)),
                ('completacion', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPreguntaModel',
            fields=[
                ('generacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tipos_pregunta', serialize=False, to='gquestions_api.generacionmodel')),
                ('pregunta_abierta', models.BooleanField(default=True)),
                ('opcion_multiple', models.BooleanField(default=True)),
                ('completacion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GeneracionTextoModel',
            fields=[
                ('id_texto', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cuerpo_texto', models.TextField(max_length=2000)),
                ('es_editado', models.BooleanField(default=False)),
                ('es_regenerado', models.BooleanField(default=False)),
                ('generacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generaciones_texto', to='gquestions_api.generacionmodel')),
            ],
        ),
        migrations.AddField(
            model_name='generacionpreguntamodel',
            name='generacion_texto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='gquestions_api.generaciontextomodel'),
        ),
        migrations.CreateModel(
            name='ExamenModel',
            fields=[
                ('id_examen', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('contestado', models.BooleanField(default=False, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('examen_configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='gquestions_api.examenconfiguracionmodel')),
                ('texto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texto_examen', to='gquestions_api.generaciontextomodel')),
            ],
        ),
        migrations.AddField(
            model_name='examenconfiguracionmodel',
            name='generacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generacion_examenes', to='gquestions_api.generacionmodel'),
        ),
        migrations.CreateModel(
            name='CalificacionUsuarioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gquestions_api.calificacionmodel')),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gquestions_api.examenmodel')),
            ],
        ),
    ]
