# Generated by Django 3.2 on 2021-05-02 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gquestions_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generacionpreguntamodel',
            name='generacion_texto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='gquestions_api.generaciontextomodel'),
        ),
    ]
