# Generated by Django 3.1.7 on 2021-03-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gquestions_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generacionusuario',
            old_name='username_id',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='usuarioexamengeneracion',
            old_name='username_id',
            new_name='username',
        ),
    ]
