# Generated by Django 3.2 on 2021-05-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gquestions_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenconfiguracionmodel',
            name='id_configuracion_examen',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
