# Generated by Django 3.2 on 2021-06-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gquestions_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuestapreguntaexamenmodel',
            old_name='generacoin_pregunta',
            new_name='generacion_pregunta',
        ),
    ]
