# Generated by Django 3.2 on 2021-04-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gquestions_api', '0002_auto_20210429_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='fecha_hora_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='examen',
            name='fecha_hora_ini',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='examen',
            name='fecha_hora_visualizacion',
            field=models.DateTimeField(),
        ),
    ]
