# Generated by Django 3.2 on 2021-05-28 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gquestions_api', '0002_alter_examenconfiguracionmodel_id_configuracion_examen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenconfiguracionmodel',
            name='generacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generacion_examenes', to='gquestions_api.generacionmodel'),
        ),
        migrations.AlterField(
            model_name='examenmodel',
            name='examen_configuracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='gquestions_api.examenconfiguracionmodel'),
        ),
        migrations.AlterField(
            model_name='generacionmodel',
            name='fecha_generacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
