# Generated by Django 3.2 on 2021-06-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gquestions_api', '0003_alter_calificacionmodel_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestapreguntaexamenmodel',
            name='respuesta_usuario',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
