# Generated by Django 3.2 on 2021-04-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gquestions_api', '0003_auto_20210429_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='id_examen',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
