# Generated by Django 3.2 on 2021-04-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gquestions_api', '0004_alter_generacion_inicio_oracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generacion',
            name='inicio_oracion',
            field=models.CharField(choices=[('Aleatorio', 'Aleatorio'), ('Completo', 'Completo')], max_length=30),
        ),
    ]
