# Generated by Django 3.2 on 2021-06-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gquestions_api', '0004_alter_respuestapreguntaexamenmodel_respuesta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestapreguntaexamenmodel',
            name='respuesta_usuario',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
