# Generated by Django 3.2 on 2021-04-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gquestions_api', '0004_alter_generaciontexto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaciontexto',
            name='cuerpo_texto',
            field=models.TextField(max_length=2000),
        ),
    ]
